#baseURL = 'https://thomas-mewily.github.io/website/'
baseURL = "http://localhost:1313/"

languageCode = 'en-us'
title = 'Mewily Website'
theme = "tailwind"
author = "Mewily"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

[params.header]
    logo = "images/logo.png"
    title = ""

[params.footer]
    since = 2025
    poweredby = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 100

  [[menu.main]]
    identifier = "games"
    name = "Games"
    url = "/games/"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

[params.social_media]

[[params.social_media.items]]
  name = "YouTube"
  url = "https://www.youtube.com/@thomasmewily4012"
  icon = "images/youtube.png"

[[params.social_media.items]]
  name = "Itch.io"
  url = "https://mewily.itch.io/"
  icon = "images/itchio.png"
