#baseURL = 'https://thomas-mewily.github.io/website/'
baseURL = "http://localhost:1313/"

languageCode = 'en-us'
title = 'Mewily Website'
theme = "tailwind"
author = "Mewily"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  keywords = "mewily, tstd, scratch, programming, games, rust"
  subtitle = ""


[params.author]
  name = "Thomas Mewily"
  email = "thomas.mewily@gmail.com"

[params.header]
    logo = "images/logo.png"
    title = ""

[params.footer]
    since = 2025
    poweredby = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog 💬"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "games"
    name = "Games 👾"
    url = "/games/"
    weight = 20


#  [[menu.main]]
#    identifier = "projects"
#    name = "Projects 💻"
#    url = "/projects/"
#    weight = 30

  [[menu.main]]
    identifier = "pixel art"
    name = "Art 🎨"
    url = "/pixel_art/"
    weight = 30

  [[menu.main]]
    identifier = "test"
    name = "Test 💻"
    url = "/test/"
    weight = 40

  [[menu.main]]
    identifier = "about"
    name = "About 🤫"
    url = "/about/"
    weight = 50

[params.social_media]
  [[params.social_media.items]]
    enabled = true
    title = "YouTube"
    link = "https://www.youtube.com/@thomasmewily4012"
    icon = "brand-youtube"


  [[params.social_media.items]]
    enabled = true
    title = "Itch.io"
    link = "https://mewily.itch.io/"
    icon = "brand-itchio"

  [[params.social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/Thomas-Mewily'


[privacy]
  [privacy.youTube]
    disable = false
    privacyEnhanced = false

ignoreLogs = ["warning-goldmark-raw-html"]


[markup]
  [markup.goldmark.renderer]
      unsafe = true
